---
- name: Install and configure httpd
  hosts: all
  remote_user: devops
  become: true

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: installed
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Install firewalld
      yum:
        name: firewalld
        state: installed
    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: enable firewall
      firewalld:
        zone: public
        service: http
        permanent: yes
        immediate: yes
        state: enabled
    - name: template server configs
      template:
        src: "templates/{{inventory_hostname}}-httpd.conf.j2"
        dest: /etc/httpd/conf.d/myconfig.conf
        owner: root
        group: root
        mode: 0644
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

- name: Deploy web service and disable proxy server
  hosts: webservers
  remote_user: devops
  become: true

  tasks:
    - name: stop apache
      service:
        name: httpd
        state: stopped
      delegate_to: "{{ item }}"
      with_items: "{{ groups['proxyservers']}}"

    - name: Deploy webpages
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: 0644
    
    - name: start apache proxy server
      service:
        name: httpd
        state: started
      delegate_to: "{{ item }}"
      with_items: "{{ groups['proxyservers']}}"  