---
- name: Deploy Apache
  hosts: webserver
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service:  httpd
    firewall_service: firewalld
    python_pkg: python-httplib2
    rule: http

  tasks:
    - name: Required pkgs
      yum:
        name:
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest

    - name: The {{ firewall_service }} service is installed
      service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: The {{ web_service }} service is installed
      service:
        name: "{{ web_service }}"
        enabled: true
        state: started

    - name: Web content is in place
      copy:
        content: "Example web content"
        dest: /var/www/html/index.html

    - name: Firewall port for {{ rule }} is open
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

- name: Verify the service is up
  hosts: localhost
  become: false
  tasks:
    - name: Ensure server is reacheable
      uri:
        url: http://servera.lab.example.com
        status_code: 200

