---
- name: Install and configure vsftpd
  hosts: ftpservers

  become: true

  vars:
    vsftpd_anon_root: /mnt/share/
    vsftpd_local_root: /mnt/share/

  roles:
    - ansible-vsftpd

  tasks:
    - name: /dev/vdb1 is partitioned
      command: >
        creates=/dev/vdb1
        parted --script /dev/vdb mklabel gpt mkpart primary 1MiB 100%
    - name: XFS exist
      filesystem:
        dev: /dev/vdb1
        fstype: xfs
        force: no

    - name: anon_root mount
      file:
        path: "{{ vsftpd_anon_root }}"
        state: directory
    - name: /dev/vdb1 is mounted
      mount:
        name: "{{ vsftpd_anon_root }}"
        src: /dev/vdb1
        fstype: xfs
        state: mounted
        dump: 1
        passno: 2
      notify: restart vsftpd

    - name: make sure
      file:
        path: "{{ vsftpd_anon_root }}"
        owner: root 
        group: root
        mode: 0755
        setype: "{{ vsftpd_setype }}"
        state: directory

    - name: Copy README to ftp anon_root
      copy:
        dest: "{{ vsftpd_anon_root }}/README"
        content: "Welcome to the FTP server at {{ ansible_fqdn }}\n"
        setype: "{{ vsftpd_setype }}"