---
- name: Install apache
  hosts: webserver
  gather_facts: no

  tasks:
    - name: gather facts
      setup:

    - name: Install required pkgs
      yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: latest

    - name: start the service
      service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"
