---
- name: Install remote facts
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
   
  tasks:
    - name: Create remote dir
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Install new fact
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"

