---
- name: Install and configure lamp
  hosts: lamp
  vars:
    firewall: firewalld
  tasks:
    - name: Include vars
      include_vars: vars/main.yml
    - name: include main task
      include: tasks/main.yml

    - name: Install firewall
      yum:
        name: "{{firewall}}"
        state: latest

    - name: start firewal
      service:
        name: "{{firewall}}"
        state: started
        enabled: true
    - name: Open port
      firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
    - name: create index.html
      copy:
        content: "{{ansible_fqdn}}({{ansible_default_ipv4.address}}) has been customized by Ansible\n"
        dest: "{{web_root}}/index.html"

