---
- name: Install remote facts
  hosts: lamp
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: Create the remote dir
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Install the new fact
      copy:
        src:  "{{ facts_file }}"
        dest: "{{ remote_dir }}/{{facts_file}}"

