---
- hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb


  tasks:
    - name: Install {{ item }}
      yum:
        name: "{{item}}"
        state: latest
      ignore_errors: yes
      with_items: ["{{web_package}}", "{{db_package}}"]

    - block:
        - name: Install {{ web_package }} package
          yum:
            name: "{{web_package}}"
            state: latest
          failed_when: web_package == "httpd"
      rescue:
        - name: Install {{ db_package }}
          yum:
            name: "{{db_package}}"
            state: latest
      always:
        - name: start {{ db_service }} 
          service:
            name: "{{db_service}}"
            state: started

    - name: check local time
      command: date
      register: com_result
      changed_when: false

    - name: Print local time
      debug:
        var: com_result["stdout"]

